/* ========================================
   FREEMOVIE.BD - MOVIE DATABASE
   Owner: Shafi Mohammad
   ======================================== */

const moviesDatabase = [
    {
        id: 1,
        title: "The Quantum Realm",
        rating: 9.2,
        votes: 25000,
        year: 2024,
        genre: ["Sci-Fi", "Thriller"],
        image: "https://images.unsplash.com/photo-1629873886876-bbfc8c3e2de3?w=400&h=600&fit=crop",
        description: "An epic journey through parallel dimensions as humanity races against time to save civilization itself. Featuring groundbreaking visual effects and a compelling narrative.",
        director: "Christopher Nolan",
        cast: ["Leonardo DiCaprio", "Anne Hathaway", "Michael Caine"],
        duration: "158 min",
        budget: "$250M",
        boxOffice: "$1.2B",
        language: "English",
        releaseDate: "March 15, 2024",
        category: "recent"
    },
    {
        id: 2,
        title: "Echoes of Tomorrow",
        rating: 8.7,
        votes: 18000,
        year: 2024,
        genre: ["Drama", "Mystery"],
        image: "https://images.unsplash.com/photo-1485095329183-d0797cdc5676?w=400&h=600&fit=crop",
        description: "A gripping tale of redemption and discovery in a near-future world.",
        director: "Denis Villeneuve",
        cast: ["Tom Hardy", "Saoirse Ronan"],
        duration: "145 min",
        budget: "$180M",
        boxOffice: "$850M",
        language: "English",
        releaseDate: "February 20, 2024",
        category: "recent"
    },
    {
        id: 3,
        title: "Midnight Horizons",
        rating: 9.4,
        votes: 31000,
        year: 2024,
        genre: ["Adventure", "Sci-Fi"],
        image: "https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?w=400&h=600&fit=crop",
        description: "An breathtaking adventure across undiscovered territories.",
        director: "James Cameron",
        cast: ["Timothée Chalamet", "Zendaya", "Oscar Isaac"],
        duration: "165 min",
        budget: "$280M",
        boxOffice: "$2.1B",
        language: "English",
        releaseDate: "January 10, 2024",
        category: "top"
    },
    {
        id: 4,
        title: "Crimson Streets",
        rating: 8.3,
        votes: 15000,
        year: 2023,
        genre: ["Crime", "Drama"],
        image: "https://images.unsplash.com/photo-1497206365907-3ff2691bef5d?w=400&h=600&fit=crop",
        description: "A neo-noir thriller set in a sprawling metropolis.",
        director: "Martin Scorsese",
        cast: ["Robert Pattinson", "Margot Robbie"],
        duration: "155 min",
        budget: "$200M",
        boxOffice: "$950M",
        language: "English",
        releaseDate: "November 5, 2023",
        category: "trending"
    },
    {
        id: 5,
        title: "Whispers in the Dark",
        rating: 8.9,
        votes: 22000,
        year: 2024,
        genre: ["Horror", "Thriller"],
        image: "https://images.unsplash.com/photo-1524985069026-5c2a440e6628?w=400&h=600&fit=crop",
        description: "A terrifying journey into the unknown depths of human fear.",
        director: "Ari Aster",
        cast: ["Thomasin McKenzie", "Bill Skarsgård"],
        duration: "142 min",
        budget: "$45M",
        boxOffice: "$320M",
        language: "English",
        releaseDate: "March 1, 2024",
        category: "trending"
    },
    {
        id: 6,
        title: "Golden Memories",
        rating: 8.5,
        votes: 19000,
        year: 2023,
        genre: ["Drama", "Romance"],
        image: "https://images.unsplash.com/photo-1506920527919-7ce8b08b1d66?w=400&h=600&fit=crop",
        description: "A touching romance spanning decades and continents.",
        director: "Luca Guadagnino",
        cast: ["Timothée Chalamet", "Armie Hammer"],
        duration: "132 min",
        budget: "$85M",
        boxOffice: "$520M",
        language: "English",
        releaseDate: "October 12, 2023",
        category: "top"
    },
    {
        id: 7,
        title: "Neon Nights",
        rating: 7.8,
        votes: 12000,
        year: 2024,
        genre: ["Action", "Cyberpunk"],
        image: "https://images.unsplash.com/photo-1519889335784-8676d14e4d9a?w=400&h=600&fit=crop",
        description: "A high-octane cyberpunk adventure in a neon-lit future.",
        director: "Yorgos Lanthimos",
        cast: ["Anya Taylor-Joy", "Harry Styles"],
        duration: "138 min",
        budget: "$120M",
        boxOffice: "$690M",
        language: "English",
        releaseDate: "February 8, 2024",
        category: "trending"
    },
    {
        id: 8,
        title: "Starlight Chronicles",
        rating: 8.6,
        votes: 20000,
        year: 2023,
        genre: ["Sci-Fi", "Adventure"],
        image: "https://images.unsplash.com/photo-1478720568477-152d9e3287d3?w=400&h=600&fit=crop",
        description: "Epic space exploration and discovery beyond the stars.",
        director: "Ridley Scott",
        cast: ["Adam Driver", "Charlize Theron"],
        duration: "159 min",
        budget: "$220M",
        boxOffice: "$1.4B",
        language: "English",
        releaseDate: "December 1, 2023",
        category: "top"
    },
    {
        id: 9,
        title: "Laugh Track",
        rating: 7.5,
        votes: 9000,
        year: 2024,
        genre: ["Comedy", "Romance"],
        image: "https://images.unsplash.com/photo-1535499738260-c8622440aae0?w=400&h=600&fit=crop",
        description: "A hilarious comedy about love, friendship, and life.",
        director: "Judd Apatow",
        cast: ["Jonah Hill", "Emma Stone"],
        duration: "115 min",
        budget: "$35M",
        boxOffice: "$280M",
        language: "English",
        releaseDate: "January 25, 2024",
        category: "recent"
    },
    {
        id: 10,
        title: "Broken Pieces",
        rating: 8.8,
        votes: 21000,
        year: 2023,
        genre: ["Drama", "Bio"],
        image: "https://images.unsplash.com/photo-1546447496-7f51e341aa08?w=400&h=600&fit=crop",
        description: "A powerful biographical drama of resilience and redemption.",
        director: "Pablo Larraín",
        cast: ["Cate Blanchett", "Michaela Jaé Rodriguez"],
        duration: "148 min",
        budget: "$95M",
        boxOffice: "$620M",
        language: "English",
        releaseDate: "November 18, 2023",
        category: "top"
    },
    {
        id: 11,
        title: "Ocean's Final Breath",
        rating: 8.1,
        votes: 14000,
        year: 2024,
        genre: ["Action", "Heist"],
        image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400&h=600&fit=crop",
        description: "A thrilling heist adventure with a plot twist at every turn.",
        director: "Steven Soderbergh",
        cast: ["Ryan Gosling", "Margot Robbie", "Brad Pitt"],
        duration: "135 min",
        budget: "$110M",
        boxOffice: "$680M",
        language: "English",
        releaseDate: "March 8, 2024",
        category: "trending"
    },
    {
        id: 12,
        title: "Eternal Flames",
        rating: 9.0,
        votes: 23000,
        year: 2024,
        genre: ["Romance", "Drama"],
        image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400&h=600&fit=crop",
        description: "A passionate love story against the backdrop of a changing world.",
        director: "Wong Kar-wai",
        cast: ["Saoirse Ronan", "Development Davis"],
        duration: "152 min",
        budget: "$105M",
        boxOffice: "$750M",
        language: "English",
        releaseDate: "February 14, 2024",
        category: "recent"
    },
    {
        id: 13,
        title: "Shadow Protocol",
        rating: 8.4,
        votes: 16000,
        year: 2023,
        genre: ["Thriller", "Spy"],
        image: "https://images.unsplash.com/photo-1576516927231-cf20d1d521f1?w=400&h=600&fit=crop",
        description: "A high-stakes espionage thriller with international intrigue.",
        director: "Tomas Alfredson",
        cast: ["Rami Malek", "Saoirse Ronan"],
        duration: "144 min",
        budget: "$115M",
        boxOffice: "$720M",
        language: "English",
        releaseDate: "October 28, 2023",
        category: "top"
    },
    {
        id: 14,
        title: "Jungle Expedition",
        rating: 7.9,
        votes: 11000,
        year: 2024,
        genre: ["Adventure", "Action"],
        image: "https://images.unsplash.com/photo-1478720568477-152d9e3287d3?w=400&h=600&fit=crop",
        description: "An action-packed adventure deep in uncharted territory.",
        director: "Jon Favreau",
        cast: ["Dwayne Johnson", "Kevin Hart"],
        duration: "128 min",
        budget: "$150M",
        boxOffice: "$820M",
        language: "English",
        releaseDate: "January 19, 2024",
        category: "trending"
    },
    {
        id: 15,
        title: "City of Glass",
        rating: 8.2,
        votes: 13000,
        year: 2023,
        genre: ["Mystery", "Thriller"],
        image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400&h=600&fit=crop",
        description: "A cerebral mystery with mind-bending twists.",
        director: "David Fincher",
        cast: ["Jesse Eisenberg", "Daisy Ridley"],
        duration: "141 min",
        budget: "$98M",
        boxOffice: "$580M",
        language: "English",
        releaseDate: "November 8, 2023",
        category: "top"
    },
    {
        id: 16,
        title: "Aurora Rising",
        rating: 8.7,
        votes: 18500,
        year: 2024,
        genre: ["Sci-Fi", "Epic"],
        image: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=400&h=600&fit=crop",
        description: "An epic sci-fi saga spanning galaxies and dimensions.",
        director: "Bong Joon-ho",
        cast: ["Song Kang-ho", "Lee Byung-hun"],
        duration: "162 min",
        budget: "$240M",
        boxOffice: "$1.35B",
        language: "Korean",
        releaseDate: "March 12, 2024",
        category: "trending"
    },
    {
        id: 17,
        title: "Interstellar",
        rating: 9.3,
        votes: 42000,
        year: 2014,
        genre: ["Sci-Fi", "Drama", "Adventure"],
        image: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=400&h=600&fit=crop",
        description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        director: "Christopher Nolan",
        cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
        duration: "169 min",
        budget: "$165M",
        boxOffice: "$731M",
        language: "English",
        releaseDate: "November 7, 2014",
        category: "top"
    },
    {
        id: 18,
        title: "Avengers: Endgame",
        rating: 8.4,
        votes: 48000,
        year: 2019,
        genre: ["Action", "Adventure", "Sci-Fi"],
        image: "https://images.unsplash.com/photo-1560109305-543149eceb16?w=400&h=600&fit=crop",
        description: "After the devastating events, the Avengers assemble once more to reverse Thanos's actions.",
        director: "Anthony & Joe Russo",
        cast: ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson"],
        duration: "181 min",
        budget: "$356M",
        boxOffice: "$2.798B",
        language: "English",
        releaseDate: "April 26, 2019",
        category: "top"
    },
    {
        id: 19,
        title: "The Dark Knight",
        rating: 9.0,
        votes: 38000,
        year: 2008,
        genre: ["Action", "Crime", "Drama"],
        image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400&h=600&fit=crop",
        description: "Batman faces the Joker, a criminal mastermind who wants to plunge Gotham into anarchy.",
        director: "Christopher Nolan",
        cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
        duration: "152 min",
        budget: "$185M",
        boxOffice: "$1.005B",
        language: "English",
        releaseDate: "July 18, 2008",
        category: "top"
    },
    {
        id: 20,
        title: "Inception",
        rating: 8.8,
        votes: 35000,
        year: 2010,
        genre: ["Action", "Sci-Fi", "Thriller"],
        image: "https://images.unsplash.com/photo-1629873886876-bbfc8c3e2de3?w=400&h=600&fit=crop",
        description: "A skilled thief who steals corporate secrets through dream-sharing technology.",
        director: "Christopher Nolan",
        cast: ["Leonardo DiCaprio", "Marion Cotillard", "Ellen Page"],
        duration: "148 min",
        budget: "$160M",
        boxOffice: "$839.5M",
        language: "English",
        releaseDate: "July 16, 2010",
        category: "top"
    },
    {
        id: 21,
        title: "Titanic",
        rating: 7.8,
        votes: 32000,
        year: 1997,
        genre: ["Romance", "Drama"],
        image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400&h=600&fit=crop",
        description: "The ill-fated maiden voyage of the RMS Titanic with a love story at its heart.",
        director: "James Cameron",
        cast: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane"],
        duration: "194 min",
        budget: "$200M",
        boxOffice: "$2.257B",
        language: "English",
        releaseDate: "December 19, 1997",
        category: "top"
    },
    {
        id: 22,
        title: "Avatar",
        rating: 7.8,
        votes: 28000,
        year: 2009,
        genre: ["Action", "Adventure", "Sci-Fi"],
        image: "https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?w=400&h=600&fit=crop",
        description: "A paraplegic Marine dispatched to the moon Pandora joins the natives to fight against exploitation.",
        director: "James Cameron",
        cast: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver"],
        duration: "162 min",
        budget: "$237M",
        boxOffice: "$2.923B",
        language: "English",
        releaseDate: "December 18, 2009",
        category: "top"
    },
    {
        id: 23,
        title: "The Matrix",
        rating: 8.7,
        votes: 30000,
        year: 1999,
        genre: ["Action", "Sci-Fi"],
        image: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=400&h=600&fit=crop",
        description: "A computer hacker learns the truth about his reality and his role in the war against controllers.",
        director: "Lana & Lilly Wachowski",
        cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
        duration: "136 min",
        budget: "$63M",
        boxOffice: "$467.2M",
        language: "English",
        releaseDate: "March 31, 1999",
        category: "top"
    },
    {
        id: 24,
        title: "Jurassic Park",
        rating: 8.1,
        votes: 26000,
        year: 1993,
        genre: ["Action", "Adventure", "Sci-Fi"],
        image: "https://images.unsplash.com/photo-1485095329183-d0797cdc5676?w=400&h=600&fit=crop",
        description: "A pragmatic paleontologist is tasked with protecting a couple of kids when dinosaurs wreak havoc.",
        director: "Steven Spielberg",
        cast: ["Sam Neill", "Laura Dern", "Jeff Goldblum"],
        duration: "127 min",
        budget: "$63M",
        boxOffice: "$1.046B",
        language: "English",
        releaseDate: "June 11, 1993",
        category: "top"
    }
];

/* Export for use in other scripts */
if (typeof module !== 'undefined' && module.exports) {
    module.exports = moviesDatabase;
}
